application: sa-emote
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: sa-emote.py
- url: /assets
  static_dir: assets
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico